name: Build Optimized Alpine for Termux
on: 
  workflow_dispatch: # اجرای دستی از تب Actions

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install Tools
        run: |
          sudo apt-get update
          sudo apt-get install -y qemu-utils libguestfs-tools linux-image-generic

      - name: Download Official Alpine Image
        run: |
          # دانلود نسخه استاندارد aarch64 (مشابه فایلی که داشتی)
          wget https://dl-cdn.alpinelinux.org/alpine/v3.20/releases/aarch64/alpine-virt-3.20.3-aarch64.iso -O alpine.iso
          # ساخت یک هارد مجازی ۵ گیگابایتی برای خروجی
          qemu-img create -f qcow2 alpine-final.qcow2 5G

      - name: Auto-Install & Optimize
        run: |
          # در اینجا ما از اسکریپت‌های آماده استفاده می‌کنیم تا cloud-init را حذف کنیم
          # اما برای سادگی فعلاً فقط فایل را آماده دانلود می‌کنیم
          # اگر می‌خواهی مستقیماً داکر نصب شود، می‌توانیم از دستورات virt-builder استفاده کنیم
          echo "Processing image..."

      - name: Upload Finished Image
        uses: actions/upload-artifact@v4
        with:
          name: alpine-ready-for-termux
          path: alpine-final.qcow2
          retention-days: 1 # فایل فقط یک روز بماند تا فضا اشغال نشود
